### ISSUE TITLE
Should we make Range a subclass of StaticRange?

### ISSUE THREAD

**Issue by chong-z** [garykac/staticrange#1]
~~According to the [StaticRange.idl](https://lists.w3.org/Archives/Public/public-editing-tf/2016Jan/0026.html) I found (not sure if that's the latest one) there are some duplicate methods with Range.~~ 

See @dtapuska comments below, do we still want to make it `interface Range : StaticRange`?

~~BTW would it be better to have the an idl inside this explainer?~~
Here is the idl https://github.com/garykac/staticrange/issues/2#issuecomment-217272202

**Comment by chong-z** [comment]
@dtapuska mentioned that `StaticRange` should be a subclass of `Range`, but [the idl](https://github.com/garykac/staticrange/issues/2#issuecomment-217272202) seems disagree. 
@garykac @ojanvafai can we have a confirmation on this question? Thanks!

**Comment by dtapuska** [comment]
I recall that we were talking about changing Range to be a subclass of StaticRange...

ie: interface StaticRange
and
interface Range : StaticRange

I don't recall what the resolution was in January.

**Comment by garykac** [comment]
I recall it being mentioned, but there were concerns about changing the definition of Range.  I don't recall details or specific concerns, however.

**Comment by chong-z** [comment]
@garykac thanks for the comments! 

I'm currently working on `StaticRange` and is blocked on this issue  (https://crrev.com/2022863002).
Can we keep these two separate for now, and maybe changing `Range` later if we decided to do so?

**Comment by garykac** [comment]
This issue was moved to w3c/staticrange#1
