### ISSUE TITLE
Define toRange() more precisely

### ISSUE THREAD

**Issue by foolip** [garykac/staticrange#4]
https://garykac.github.io/staticrange/#dom-staticrange-torange

> Returns a new Range with the same start and end as the context object.
>
> This is a convenience method to up-convert a StaticRange into a full-featured Range object that can be used when the application requires the additional functionality provided by a Range.
>
> It is equivalent to:
>
> var newRange = document.createRange()
> newRange.selStart(staticRange.startContainer, staticRange.startOffset);
> newRange.selEnd(staticRange.endContainer, staticRange.endOffset);

It's not clear which parts of this are intended to be normative. At first glance, I would take only "Returns a new Range with the same start and end as the context object" to be a requirement on implementations, and the rest to be non-normative explanatory text.

It would be clearer as an algorithm:
1. Let *range* be a new [range](https://dom.spec.whatwg.org/#concept-range)
2. [Set the start](https://dom.spec.whatwg.org/#concept-range-bp-set) of *range* to ...
3. [Set the end](https://dom.spec.whatwg.org/#concept-range-bp-set) of *range* to ...
 https://dom.spec.whatwg.org/#concept-range-bp-set
4. Return *range*

@annevk @domenic, do we like "Rethrow any exceptions" these days?

**Comment by annevk** [comment]
If you use https://infra.spec.whatwg.org/ there's no need to rethrow, otherwise you need to define your own conventions (which I'd recommend against).

**Comment by foolip** [comment]
`toRange()` was removed in https://github.com/garykac/staticrange/commit/c191c84e7e2a765c89b3d87295b4e62b63f05e06
