### ISSUE TITLE
"is valid" algorithm uses a concept of "size of" that is not defined

### ISSUE THREAD

**Issue by bzbarsky** [garykac/staticrange#7]
Things like:

> If sr’s startOffset is greater than the size of the startContainer,

Presumably it means "the number of children of the startContainer".  That's the terminology other specs use for this.

**Comment by bzbarsky** [comment]
Actually, no, that's not right for textnodes.

What you probably want is https://dom.spec.whatwg.org/#concept-node-length complete with a link to it.

**Comment by garykac** [comment]
This issue was moved to w3c/staticrange#5
